name: Release to dev

on:
  push:
    branches:
    - main

env:
  GOOGLECLOUD_REGION: "asia-northeast1"

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/tests.yaml

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLECLOUD_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Update configs'
      run: ./deploy/pre-build.sh ${{ env.GOOGLECLOUD_REGION }}

    - name: 'Create the firebase.js'
      run: echo "${{ secrets.GOOGLECLOUD_FIREBASE }}" > src/public/js/app/firebase.js

    - name: 'Release to Dev'
      run: gcloud run deploy dev --region ${{ env.GOOGLECLOUD_REGION }} --source src --service-account "app-client@${{ secrets.GOOGLECLOUD_PROJECT }}.iam.gserviceaccount.com"
