name: Tests

on:
  workflow_call:
  push:
    paths-ignore:
      - '**/*.md'
    branches-ignore:
      - main

jobs:
  revel-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install Revel
        run: go install github.com/revel/cmd/revel@latest

      - name: Test
        run: revel test -a src
